/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AccountRouteImport } from './routes/account'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'
import { Route as SaleSlugRouteImport } from './routes/sale.$slug'
import { Route as LibraryTokenRouteImport } from './routes/library.$token'
import { Route as GoCodeRouteImport } from './routes/go.$code'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardMarketingRouteImport } from './routes/dashboard.marketing'
import { Route as DashboardLoginRouteImport } from './routes/dashboard.login'
import { Route as DashboardCampaignLinksRouteImport } from './routes/dashboard.campaign-links'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as DashboardSalesIndexRouteImport } from './routes/dashboard.sales.index'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard.products.index'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard.orders.index'
import { Route as DashboardCustomersIndexRouteImport } from './routes/dashboard.customers.index'
import { Route as ShopPSlugRouteImport } from './routes/shop.p.$slug'
import { Route as DashboardSalesNewRouteImport } from './routes/dashboard.sales.new'
import { Route as DashboardSalesIdRouteImport } from './routes/dashboard.sales.$id'
import { Route as DashboardProductsNewRouteImport } from './routes/dashboard.products.new'
import { Route as DashboardProductsIdRouteImport } from './routes/dashboard.products.$id'
import { Route as DashboardOrdersIdRouteImport } from './routes/dashboard.orders.$id'
import { Route as DashboardCustomersIdRouteImport } from './routes/dashboard.customers.$id'
import { Route as ApiPublicDownloadRouteImport } from './routes/api/public/download'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleSlugRoute = SaleSlugRouteImport.update({
  id: '/sale/$slug',
  path: '/sale/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryTokenRoute = LibraryTokenRouteImport.update({
  id: '/library/$token',
  path: '/library/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GoCodeRoute = GoCodeRouteImport.update({
  id: '/go/$code',
  path: '/go/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketingRoute = DashboardMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignLinksRoute = DashboardCampaignLinksRouteImport.update({
  id: '/campaign-links',
  path: '/campaign-links',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const DashboardSalesIndexRoute = DashboardSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersIndexRoute = DashboardCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => DashboardRoute,
} as any)
const ShopPSlugRoute = ShopPSlugRouteImport.update({
  id: '/shop/p/$slug',
  path: '/shop/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSalesNewRoute = DashboardSalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSalesIdRoute = DashboardSalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsNewRoute = DashboardProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsIdRoute = DashboardProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersIdRoute = DashboardOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersIdRoute = DashboardCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicDownloadRoute = ApiPublicDownloadRouteImport.update({
  id: '/api/public/download',
  path: '/api/public/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/account': typeof AccountRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/our-story': typeof OurStoryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/account/orders': typeof AccountOrdersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/campaign-links': typeof DashboardCampaignLinksRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/go/$code': typeof GoCodeRoute
  '/library/$token': typeof LibraryTokenRoute
  '/sale/$slug': typeof SaleSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/account/': typeof AccountIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/dashboard/customers/$id': typeof DashboardCustomersIdRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
  '/dashboard/products/$id': typeof DashboardProductsIdRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/sales/$id': typeof DashboardSalesIdRoute
  '/dashboard/sales/new': typeof DashboardSalesNewRoute
  '/shop/p/$slug': typeof ShopPSlugRoute
  '/dashboard/customers/': typeof DashboardCustomersIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/sales/': typeof DashboardSalesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/contact-us': typeof ContactUsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/our-story': typeof OurStoryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/account/orders': typeof AccountOrdersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/campaign-links': typeof DashboardCampaignLinksRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/go/$code': typeof GoCodeRoute
  '/library/$token': typeof LibraryTokenRoute
  '/sale/$slug': typeof SaleSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/account': typeof AccountIndexRoute
  '/blog': typeof BlogIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/shop': typeof ShopIndexRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/dashboard/customers/$id': typeof DashboardCustomersIdRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
  '/dashboard/products/$id': typeof DashboardProductsIdRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/sales/$id': typeof DashboardSalesIdRoute
  '/dashboard/sales/new': typeof DashboardSalesNewRoute
  '/shop/p/$slug': typeof ShopPSlugRoute
  '/dashboard/customers': typeof DashboardCustomersIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/sales': typeof DashboardSalesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/account': typeof AccountRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/our-story': typeof OurStoryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/account/orders': typeof AccountOrdersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/campaign-links': typeof DashboardCampaignLinksRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/go/$code': typeof GoCodeRoute
  '/library/$token': typeof LibraryTokenRoute
  '/sale/$slug': typeof SaleSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/account/': typeof AccountIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/dashboard/customers/$id': typeof DashboardCustomersIdRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
  '/dashboard/products/$id': typeof DashboardProductsIdRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/sales/$id': typeof DashboardSalesIdRoute
  '/dashboard/sales/new': typeof DashboardSalesNewRoute
  '/shop/p/$slug': typeof ShopPSlugRoute
  '/dashboard/customers/': typeof DashboardCustomersIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/sales/': typeof DashboardSalesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/account'
    | '/contact-us'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/llms.txt'
    | '/login'
    | '/our-story'
    | '/privacy-policy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/account/orders'
    | '/blog/$slug'
    | '/checkout/return'
    | '/dashboard/analytics'
    | '/dashboard/campaign-links'
    | '/dashboard/login'
    | '/dashboard/marketing'
    | '/dashboard/settings'
    | '/go/$code'
    | '/library/$token'
    | '/sale/$slug'
    | '/shop/$category'
    | '/account/'
    | '/blog/'
    | '/checkout/'
    | '/dashboard/'
    | '/shop/'
    | '/api/public/download'
    | '/dashboard/customers/$id'
    | '/dashboard/orders/$id'
    | '/dashboard/products/$id'
    | '/dashboard/products/new'
    | '/dashboard/sales/$id'
    | '/dashboard/sales/new'
    | '/shop/p/$slug'
    | '/dashboard/customers/'
    | '/dashboard/orders/'
    | '/dashboard/products/'
    | '/dashboard/sales/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/contact-us'
    | '/faq'
    | '/forgot-password'
    | '/llms.txt'
    | '/login'
    | '/our-story'
    | '/privacy-policy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/account/orders'
    | '/blog/$slug'
    | '/checkout/return'
    | '/dashboard/analytics'
    | '/dashboard/campaign-links'
    | '/dashboard/login'
    | '/dashboard/marketing'
    | '/dashboard/settings'
    | '/go/$code'
    | '/library/$token'
    | '/sale/$slug'
    | '/shop/$category'
    | '/account'
    | '/blog'
    | '/checkout'
    | '/dashboard'
    | '/shop'
    | '/api/public/download'
    | '/dashboard/customers/$id'
    | '/dashboard/orders/$id'
    | '/dashboard/products/$id'
    | '/dashboard/products/new'
    | '/dashboard/sales/$id'
    | '/dashboard/sales/new'
    | '/shop/p/$slug'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/sales'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/account'
    | '/contact-us'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/llms.txt'
    | '/login'
    | '/our-story'
    | '/privacy-policy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/account/orders'
    | '/blog/$slug'
    | '/checkout/return'
    | '/dashboard/analytics'
    | '/dashboard/campaign-links'
    | '/dashboard/login'
    | '/dashboard/marketing'
    | '/dashboard/settings'
    | '/go/$code'
    | '/library/$token'
    | '/sale/$slug'
    | '/shop/$category'
    | '/account/'
    | '/blog/'
    | '/checkout/'
    | '/dashboard/'
    | '/shop/'
    | '/api/public/download'
    | '/dashboard/customers/$id'
    | '/dashboard/orders/$id'
    | '/dashboard/products/$id'
    | '/dashboard/products/new'
    | '/dashboard/sales/$id'
    | '/dashboard/sales/new'
    | '/shop/p/$slug'
    | '/dashboard/customers/'
    | '/dashboard/orders/'
    | '/dashboard/products/'
    | '/dashboard/sales/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AccountRoute: typeof AccountRouteWithChildren
  ContactUsRoute: typeof ContactUsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  OurStoryRoute: typeof OurStoryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  GoCodeRoute: typeof GoCodeRoute
  LibraryTokenRoute: typeof LibraryTokenRoute
  SaleSlugRoute: typeof SaleSlugRoute
  ShopCategoryRoute: typeof ShopCategoryRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ApiPublicDownloadRoute: typeof ApiPublicDownloadRoute
  ShopPSlugRoute: typeof ShopPSlugRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/shop/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale/$slug': {
      id: '/sale/$slug'
      path: '/sale/$slug'
      fullPath: '/sale/$slug'
      preLoaderRoute: typeof SaleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$token': {
      id: '/library/$token'
      path: '/library/$token'
      fullPath: '/library/$token'
      preLoaderRoute: typeof LibraryTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$code': {
      id: '/go/$code'
      path: '/go/$code'
      fullPath: '/go/$code'
      preLoaderRoute: typeof GoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketing': {
      id: '/dashboard/marketing'
      path: '/marketing'
      fullPath: '/dashboard/marketing'
      preLoaderRoute: typeof DashboardMarketingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaign-links': {
      id: '/dashboard/campaign-links'
      path: '/campaign-links'
      fullPath: '/dashboard/campaign-links'
      preLoaderRoute: typeof DashboardCampaignLinksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/dashboard/sales/': {
      id: '/dashboard/sales/'
      path: '/sales'
      fullPath: '/dashboard/sales/'
      preLoaderRoute: typeof DashboardSalesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers/': {
      id: '/dashboard/customers/'
      path: '/customers'
      fullPath: '/dashboard/customers/'
      preLoaderRoute: typeof DashboardCustomersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/shop/p/$slug': {
      id: '/shop/p/$slug'
      path: '/shop/p/$slug'
      fullPath: '/shop/p/$slug'
      preLoaderRoute: typeof ShopPSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sales/new': {
      id: '/dashboard/sales/new'
      path: '/sales/new'
      fullPath: '/dashboard/sales/new'
      preLoaderRoute: typeof DashboardSalesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sales/$id': {
      id: '/dashboard/sales/$id'
      path: '/sales/$id'
      fullPath: '/dashboard/sales/$id'
      preLoaderRoute: typeof DashboardSalesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/new': {
      id: '/dashboard/products/new'
      path: '/products/new'
      fullPath: '/dashboard/products/new'
      preLoaderRoute: typeof DashboardProductsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/$id': {
      id: '/dashboard/products/$id'
      path: '/products/$id'
      fullPath: '/dashboard/products/$id'
      preLoaderRoute: typeof DashboardProductsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders/$id': {
      id: '/dashboard/orders/$id'
      path: '/orders/$id'
      fullPath: '/dashboard/orders/$id'
      preLoaderRoute: typeof DashboardOrdersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers/$id': {
      id: '/dashboard/customers/$id'
      path: '/customers/$id'
      fullPath: '/dashboard/customers/$id'
      preLoaderRoute: typeof DashboardCustomersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/download': {
      id: '/api/public/download'
      path: '/api/public/download'
      fullPath: '/api/public/download'
      preLoaderRoute: typeof ApiPublicDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersRoute: AccountOrdersRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCampaignLinksRoute: typeof DashboardCampaignLinksRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardMarketingRoute: typeof DashboardMarketingRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCustomersIdRoute: typeof DashboardCustomersIdRoute
  DashboardOrdersIdRoute: typeof DashboardOrdersIdRoute
  DashboardProductsIdRoute: typeof DashboardProductsIdRoute
  DashboardProductsNewRoute: typeof DashboardProductsNewRoute
  DashboardSalesIdRoute: typeof DashboardSalesIdRoute
  DashboardSalesNewRoute: typeof DashboardSalesNewRoute
  DashboardCustomersIndexRoute: typeof DashboardCustomersIndexRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardSalesIndexRoute: typeof DashboardSalesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCampaignLinksRoute: DashboardCampaignLinksRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardMarketingRoute: DashboardMarketingRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCustomersIdRoute: DashboardCustomersIdRoute,
  DashboardOrdersIdRoute: DashboardOrdersIdRoute,
  DashboardProductsIdRoute: DashboardProductsIdRoute,
  DashboardProductsNewRoute: DashboardProductsNewRoute,
  DashboardSalesIdRoute: DashboardSalesIdRoute,
  DashboardSalesNewRoute: DashboardSalesNewRoute,
  DashboardCustomersIndexRoute: DashboardCustomersIndexRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardSalesIndexRoute: DashboardSalesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AccountRoute: AccountRouteWithChildren,
  ContactUsRoute: ContactUsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  OurStoryRoute: OurStoryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  GoCodeRoute: GoCodeRoute,
  LibraryTokenRoute: LibraryTokenRoute,
  SaleSlugRoute: SaleSlugRoute,
  ShopCategoryRoute: ShopCategoryRoute,
  BlogIndexRoute: BlogIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  ApiPublicDownloadRoute: ApiPublicDownloadRoute,
  ShopPSlugRoute: ShopPSlugRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
