CREATE TABLE public.storefront_pageviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  path TEXT NOT NULL CHECK (char_length(path) BETWEEN 1 AND 500),
  referrer TEXT,
  visitor_hash TEXT,
  is_bot BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX storefront_pageviews_visitor_created_idx
  ON public.storefront_pageviews (visitor_hash, created_at);
CREATE INDEX storefront_pageviews_path_created_idx
  ON public.storefront_pageviews (path, created_at);

ALTER TABLE public.storefront_pageviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can view storefront pageviews"
  ON public.storefront_pageviews
  FOR SELECT
  TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::public.app_role));

GRANT SELECT ON public.storefront_pageviews TO authenticated;
GRANT ALL ON public.storefront_pageviews TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.storefront_pageviews_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.storefront_visit_metrics(
  _start_at TIMESTAMPTZ,
  _end_at TIMESTAMPTZ
)
RETURNS TABLE(pageviews BIGINT, unique_sessions BIGINT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin'::public.app_role) THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  RETURN QUERY
  WITH ordered AS (
    SELECT
      created_at,
      visitor_hash,
      lag(created_at) OVER (
        PARTITION BY visitor_hash
        ORDER BY created_at
      ) AS previous_at
    FROM public.storefront_pageviews
    WHERE created_at >= _start_at - interval '30 minutes'
      AND created_at < _end_at
      AND is_bot = false
      AND visitor_hash IS NOT NULL
  )
  SELECT
    count(*) FILTER (WHERE created_at >= _start_at)::BIGINT AS pageviews,
    count(*) FILTER (
      WHERE created_at >= _start_at
        AND (
          previous_at IS NULL
          OR created_at - previous_at > interval '30 minutes'
        )
    )::BIGINT AS unique_sessions
  FROM ordered;
END;
$$;

REVOKE ALL ON FUNCTION public.storefront_visit_metrics(TIMESTAMPTZ, TIMESTAMPTZ) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.storefront_visit_metrics(TIMESTAMPTZ, TIMESTAMPTZ) TO authenticated;
